### Module 3: Array Manipulation

#### 6. **Joining and Splitting Arrays**

**Joining Arrays**

Joining arrays involves combining multiple arrays into a single array. This can be done along existing or new axes, depending on the operation used.

1. **`concatenate()`**
   - **Purpose:** Combines multiple arrays along a specified axis, either horizontally or vertically.
   - **Axis:**
     - `axis=0`: Joins arrays along rows (vertical concatenation).
     - `axis=1`: Joins arrays along columns (horizontal concatenation).
   - **Use Case:** Useful for merging datasets or extending an array.
   - **Example:**
     ```python
     import numpy as np

     arr1 = np.array([1, 2, 3])
     arr2 = np.array([4, 5, 6])
     result = np.concatenate((arr1, arr2))
     print(result)  # Output: [1 2 3 4 5 6]
     ```

2. **`stack()`**
   - **Purpose:** Joins arrays along a new axis, creating a higher-dimensional array.
   - **Axis:**
     - `axis=0`: Stacks arrays along a new first axis.
     - `axis=1`: Stacks arrays along a new second axis.
   - **Use Case:** Useful for creating a batch of arrays or multi-dimensional arrays from single-dimensional arrays.
   - **Example:**
     ```python
     import numpy as np

     arr1 = np.array([1, 2, 3])
     arr2 = np.array([4, 5, 6])
     result = np.stack((arr1, arr2), axis=0)
     print(result)
     # Output:
     # [[1 2 3]
     #  [4 5 6]]
     ```

3. **`hstack()`**
   - **Purpose:** Horizontally stacks arrays (column-wise). It is a shorthand for concatenation along `axis=1`.
   - **Use Case:** Useful for combining arrays with the same number of rows.
   - **Example:**
     ```python
     import numpy as np

     arr1 = np.array([[1], [2], [3]])
     arr2 = np.array([[4], [5], [6]])
     result = np.hstack((arr1, arr2))
     print(result)
     # Output:
     # [[1 4]
     #  [2 5]
     #  [3 6]]
     ```

4. **`vstack()`**
   - **Purpose:** Vertically stacks arrays (row-wise). It is a shorthand for concatenation along `axis=0`.
   - **Use Case:** Useful for combining arrays with the same number of columns.
   - **Example:**
     ```python
     import numpy as np

     arr1 = np.array([1, 2, 3])
     arr2 = np.array([4, 5, 6])
     result = np.vstack((arr1, arr2))
     print(result)
     # Output:
     # [[1 2 3]
     #  [4 5 6]]
     ```

**Splitting Arrays**

Splitting arrays involves dividing a single array into multiple sub-arrays. This can be done along existing axes, resulting in evenly or unevenly sized sub-arrays.

1. **`split()`**
   - **Purpose:** Divides an array into multiple sub-arrays along a specified axis.
   - **Parameters:**
     - `indices_or_sections`: Specifies the indices where the splits should occur or the number of equal sections.
     - `axis`: The axis along which to split.
   - **Use Case:** Useful for breaking down large arrays into smaller, manageable parts.
   - **Example:**
     ```python
     import numpy as np

     arr = np.array([1, 2, 3, 4, 5, 6])
     result = np.split(arr, 3)
     print(result)
     # Output: [array([1, 2]), array([3, 4]), array([5, 6])]
     ```

2. **`hsplit()`**
   - **Purpose:** Splits a 2D array into multiple sub-arrays horizontally (column-wise).
   - **Parameters:**
     - `indices_or_sections`: Specifies the indices or number of sections.
   - **Use Case:** Useful for dividing matrices into smaller matrices along columns.
   - **Example:**
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     result = np.hsplit(arr, 3)
     print(result)
     # Output:
     # [array([[1],
     #        [4]]), array([[2],
     #                     [5]]), array([[3],
     #                                  [6]])]
     ```

3. **`vsplit()`**
   - **Purpose:** Splits a 2D array into multiple sub-arrays vertically (row-wise).
   - **Parameters:**
     - `indices_or_sections`: Specifies the indices or number of sections.
   - **Use Case:** Useful for dividing matrices into smaller matrices along rows.
   - **Example:**
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
     result = np.vsplit(arr, 3)
     print(result)
     # Output:
     # [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
     ```

