### Module 5: Advanced Topics

#### 10. **Broadcasting**

Broadcasting is a powerful mechanism in NumPy that allows operations on arrays of different shapes. It enables element-wise operations without the need for explicit looping.

1. **Rules of Broadcasting**
   - **Rule 1:** If arrays have a different number of dimensions, prepend the shape of the smaller-dimensional array with ones until both shapes are the same.
   - **Rule 2:** The dimensions of the arrays must either be the same or one of them must be 1. If not, broadcasting fails.
   - **Rule 3:** Arrays are broadcasted along dimensions with size 1 to match the size of the other array's dimensions.

2. **Practical Applications**
   - **Example 1:** Adding a scalar to an array.
     ```python
     import numpy as np

     array = np.array([1, 2, 3])
     result = array + 5
     print(result)  # Output: [6 7 8]
     ```
   - **Example 2:** Adding a 2D array to a 1D array.
     ```python
     import numpy as np

     array_2d = np.array([[1, 2, 3], [4, 5, 6]])
     array_1d = np.array([10, 20, 30])
     result = array_2d + array_1d
     print(result)
     # Output:
     # [[11 22 33]
     #  [14 25 36]]
     ```

#### 11. **Fancy Indexing and Index Tricks**

Fancy indexing and index tricks provide advanced ways to access and manipulate array elements in NumPy.

1. **Using Integer Arrays for Indexing**
   - **Purpose:** Allows selecting specific elements from an array using an array of indices.
   - **Example:**
     ```python
     import numpy as np

     array = np.array([10, 20, 30, 40, 50])
     indices = np.array([1, 3])
     result = array[indices]
     print(result)  # Output: [20 40]
     ```

2. **`ix_` and `np.ogrid`**
   - **Purpose:** Used for advanced indexing and creating mesh grids for more complex indexing operations.
   - **`ix_`:** Creates a mesh grid from the provided arrays.
     ```python
     import numpy as np

     x = np.array([1, 2, 3])
     y = np.array([4, 5])
     grid = np.ix_(x, y)
     print(grid)
     # Output:
     # (array([[1],
     #        [2],
     #        [3]]),
     #  array([[4, 5]]))
     ```
   - **`np.ogrid`:** Creates an open mesh grid which is useful for indexing into arrays.
     ```python
     import numpy as np

     x, y = np.ogrid[0:3, 0:4]
     print(x)
     # Output:
     # [[0]
     #  [1]
     #  [2]]
     print(y)
     # Output:
     # [[0 1 2 3]]
     ```

#### 12. **Structured Arrays**

Structured arrays allow you to create arrays with mixed data types, similar to database records or data frames in pandas.

1. **Creating Structured Arrays**
   - **Purpose:** Allows for the creation of arrays where each element can be a compound of different types (e.g., integers, floats, strings).
   - **Example:**
     ```python
     import numpy as np

     dtype = [('name', 'S10'), ('age', 'i4')]
     values = [('Alice', 25), ('Bob', 30)]
     structured_array = np.array(values, dtype=dtype)
     print(structured_array)
     # Output:
     # [(b'Alice', 25) (b'Bob', 30)]
     ```

2. **Accessing and Modifying Structured Arrays**
   - **Purpose:** Allows access and modification of individual fields within structured arrays.
   - **Example:**
     ```python
     import numpy as np

     dtype = [('name', 'S10'), ('age', 'i4')]
     values = [('Alice', 25), ('Bob', 30)]
     structured_array = np.array(values, dtype=dtype)
     
     # Accessing a field
     names = structured_array['name']
     print("Names:", names)  # Output: Names: [b'Alice' b'Bob']
     
     # Modifying a field
     structured_array['age'][1] = 31
     print(structured_array)
     # Output:
     # [(b'Alice', 25) (b'Bob', 31)]
     ```

### Module 6: Working with External Data

Handling external data involves reading from and writing to various file formats, which is crucial for data preprocessing and analysis.

#### 13. **Reading and Writing Data**

1. **`genfromtxt()` and `loadtxt()`**
   - **Purpose:** Functions for reading text files with numerical data.
   - **`genfromtxt()`:** Reads data from a text file, allowing for missing values and more complex data parsing.
     ```python
     import numpy as np

     data = np.genfromtxt('data.txt', delimiter=',', dtype=None, encoding=None)
     print(data)
     # Output: Contents of 'data.txt'
     ```
   - **`loadtxt()`:** Reads data from a text file where data is organized in a structured format.
     ```python
     import numpy as np

     data = np.loadtxt('data.txt', delimiter=',')
     print(data)
     # Output: Contents of 'data.txt'
     ```

2. **`save()`, `savez()`, and `savetxt()`**
   - **Purpose:** Functions for saving NumPy arrays to files.
   - **`save()`:** Saves a single array to a binary file in NumPy `.npy` format.
     ```python
     import numpy as np

     array = np.array([1, 2, 3, 4])
     np.save('array.npy', array)
     ```
   - **`savez()`:** Saves multiple arrays into a single `.npz` file.
     ```python
     import numpy as np

     array1 = np.array([1, 2, 3])
     array2 = np.array([4, 5, 6])
     np.savez('arrays.npz', array1=array1, array2=array2)
     ```
   - **`savetxt()`:** Saves an array to a text file.
     ```python
     import numpy as np

     array = np.array([1, 2, 3, 4])
     np.savetxt('array.txt', array)
     ```


